# Generated by Django 4.1.1 on 2022-10-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="phone",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
