# Generated by Django 4.1.1 on 2022-10-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0002_alter_phonebook_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="phone",
            field=models.SlugField(max_length=100),
        ),
    ]
