# Generated by Django 4.1.1 on 2022-10-15 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0005_alter_phonebook_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonebook",
            options={"ordering": ["-create_at"], "verbose_name": "Contact", "verbose_name_plural": "Phone Book"},
        ),
    ]
