# Generated by Django 4.1.3 on 2022-11-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone_book", "0006_alter_phonebook_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonebook",
            options={"ordering": ["-create_at"]},
        ),
    ]
