# Generated by Django 4.1.1 on 2022-10-15 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminuser",
            options={"verbose_name": "User", "verbose_name_plural": "Admin User"},
        ),
    ]
